feat: add the image builder with layer support

diff --git a/dist/bin/vedv b/dist/bin/vedv
--- a/dist/bin/vedv
+++ b/dist/bin/vedv
@@ -3,7 +3,7 @@
 # A tool for developing with reproducible virtual machines environments
 #
 
-set -euEo pipefail
+set -eu
 
 # CONSTANTS
 readonly __VEDV_SCRIPT_NAME="$(basename "${0}")"
@@ -11,9 +11,21 @@ readonly __VEDV_DIST_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 readonly __VEDV_LIB_PATH="${__VEDV_DIST_PATH}/lib/vedv"
 readonly __VEDV_COMPONENTS_PATH="${__VEDV_DIST_PATH}/lib/vedv/components"
 readonly __VEDV_HYPERVISORS_PATH="${__VEDV_DIST_PATH}/lib/vedv/hypervisors"
+readonly VEDV_CONFIG_DIR="${__VEDV_DIST_PATH}/etc/vedv"
+readonly VEDV_CONFIG="${VEDV_CONFIG_DIR}/vedv.env"
+
+if [[ -f "$VEDV_CONFIG" ]]; then source "$VEDV_CONFIG"; fi
+
+# ENVIRONMENT
+: "${VEDV_HADOLINT_ENABLED:="${HADOLINT_ENABLED:-true}"}"
+: "${VEDV_HADOLINT_CONFIG:="${HADOLINT_CONFIG:-"${VEDV_CONFIG_DIR}/hadolint.yaml"}"}"
+: "${VEDV_SSH_USER:="${SSH_USER:-vedv}"}"
+: "${VEDV_SSH_PASSWORD:="${SSH_PASSWORD:-"$VEDV_SSH_USER"}"}"
+: "${VEDV_SSH_IP:="${SSH_IP:-127.0.0.1}"}"
 
 # INCLUDE
 . "${__VEDV_LIB_PATH}/utils.bash"
+. "${__VEDV_LIB_PATH}/ssh-client.bash"
 . "${__VEDV_LIB_PATH}/vedv.bash"
 for f in "${__VEDV_COMPONENTS_PATH}/"*/*.bash; do . "$f"; done
 
@@ -49,7 +61,7 @@ vedv::__on_exit() {
 
 vedv::__run_cmd() {
   # IMPL: test this function
-
+  # TODO: change if [[ $# == 0 ]]; then; set -- '-h'; fi
   [[ $# == 0 ]] && set -- '-h'
 
   if [[ "${1:-}" == @(-h|--help) ]]; then
@@ -77,7 +89,12 @@ vedv::__run_cmd() {
   . "${__VEDV_HYPERVISORS_PATH}/${hypervisor}.bash"
 
   # initialize components
-  vedv::image_service::constructor "$hypervisor"
+
+  vedv::image_entity::constructor "$hypervisor"
+  vedv::image_cache_entity::constructor "$hypervisor"
+  vedv::image_vedvfile_service::constructor "$hypervisor" "$VEDV_HADOLINT_ENABLED"
+  vedv::image_builder::constructor "$hypervisor" "$VEDV_SSH_USER" "$VEDV_SSH_PASSWORD" "$VEDV_SSH_IP"
+  vedv::image_service::constructor "$hypervisor" "$VEDV_SSH_IP"
   vedv::image_command::constructor "$__VEDV_SCRIPT_NAME"
 
   vedv::container_service::constructor "$hypervisor"
@@ -98,9 +115,9 @@ vedv::__run_cmd() {
       vedv::container_command::run_cmd "$@"
       return $?
       ;;
-    # ERROR
     *)
-      echo -e "Invalid parameter: ${1}\n" >&2
+      # TODO: use err
+      err "Invalid parameter: ${1}\n"
       vedv::__help
       return 10
       ;;
diff --git a/tools/untested b/tools/untested
--- a/tools/untested
+++ b/tools/untested
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+# shellcheck disable=SC2001
 set -eu
 
 # cd to the script's directory
@@ -15,22 +15,27 @@ BASH_FILE_PATH="$BASH_FILE_NAME"
 
 if [[ ! -f "$BASH_FILE_PATH" ]]; then
   BASH_FILE_PATH="$(find . -name "$BASH_FILE_NAME" -print | head -n 1)"
+  readonly BASH_FILE_PATH
   if [[ -z "$BASH_FILE_PATH" ]]; then
     echo "File '$BASH_FILE_NAME' not found in the current directory" >&2
     exit 1
   fi
 fi
-readonly BASH_FILE_PATH
 
-BASH_FILE_BASENAME="${BASH_FILE_NAME##*/}"
-readonly BASH_FILE_BASENAME="${BASH_FILE_BASENAME%.bash}.bats"
+BATS_FILE_NAME="${BASH_FILE_NAME##*/}"
+readonly BATS_FILE_NAME="${BATS_FILE_NAME%.bash}.bats"
 
-readonly BATS_FILE_PATH="$(find . -name "${BASH_FILE_BASENAME}" -print | head -n 1)"
+BATS_FILE_PATH="$(find . -name "${BATS_FILE_NAME}" -print | head -n 1)"
+readonly BATS_FILE_PATH
+
 if [[ -z "$BATS_FILE_PATH" ]]; then
-  echo "File '${1%.bash}.bats' not found in the current directory" >&2
+  echo "File '${BATS_FILE_NAME}' not found in the current directory" >&2
   exit 1
 fi
-readonly FUNCTION_NAMES=$(grep -Po "^\s*\w+(\w|\d|_|:)+\(\s*\)" "$BASH_FILE_PATH" | sed -e 's/^\s*//' -e 's/(\s*)\s*//')
+
+FUNCTION_NAMES=$(nl -b a -s '  ' -w 1 "$BASH_FILE_PATH" | grep -Po "^\d+\s*\w+(\w|\d|_|:)+\(\s*\)" | sed 's/(\s*)\s*$//')
+readonly FUNCTION_NAMES
+
 if [[ -z "$FUNCTION_NAMES" ]]; then
   echo "No function declarations found in '$BASH_FILE_PATH'"
   exit 0
@@ -39,11 +44,21 @@ fi
 declare -p PWD BASH_FILE_PATH BATS_FILE_PATH
 echo
 # Loop through all the function declarations in file.bash
+declare -i function_counter=0
+
 while read -r function_name; do
   # Check if the function name exists in file.bats
-  if ! grep -qP "^\s*@test\s+(\"|')\s*${function_name}\(\s*\).*(\"|')" "$BATS_FILE_PATH"; then
+  if ! grep -qP "^\s*@test\s+(\"|')\s*$(echo "$function_name" | sed 's/^[[:digit:]]\+\s*//')\s*\(\s*\).*(\"|')" "$BATS_FILE_PATH"; then
     # If not, output the function name
-    echo "${function_name}()"
+    ((function_counter += 1))
+    line_number="$(grep -Po '^\d+' <<<"$function_name")"
+    function_name_only="$(sed 's/[[:digit:]]\+\s*//' <<<"$function_name")"
+
+    echo "${function_counter} ${function_name_only}()"
+    echo "  ${BASH_FILE_PATH}:${line_number}"
+    echo
   fi
 done <<<"$FUNCTION_NAMES"
 echo
+
+echo "${function_counter} untested functions"
